export const teachers = [
  {
    name: '林映辰',
    title: '副教授',
    department: '資訊工程學系',
    email: 'yingchen.lin@example.edu',
    office: '資訊館 R512',
    bio: '專注於可解釋機器學習與電腦視覺應用，研究如何讓人工智慧模型的判斷更透明，並帶領學生將技術運用於校園學習與公共服務情境之中。',
    avatarColor: '#2563EB',
    expertise: ['人工智慧', '機器學習', '電腦視覺'],
    courses: ['人工智慧概論', '機器學習'],
  },
  {
    name: '陳柏岳',
    title: '教授',
    department: '資訊工程學系',
    email: 'boyue.chen@example.edu',
    office: '資訊館 R608',
    bio: '研究大型資料庫系統、資料工程與查詢最佳化，關注資料品質及系統效能之間的平衡，也鼓勵學生透過真實案例培養資料建模與問題分析能力。',
    avatarColor: '#0F766E',
    expertise: ['資料庫', '資料工程', '查詢最佳化'],
    courses: ['資料庫系統', '進階資料庫'],
  },
  {
    name: '黃思妤',
    title: '助理教授',
    department: '資訊工程學系',
    email: 'siyu.huang@example.edu',
    office: '資訊館 R407',
    bio: '投入資訊安全、網路攻防與軟體漏洞分析研究，重視從安全設計出發建立可靠系統，並透過實作課程協助學生理解常見攻擊方法與防禦思維。',
    avatarColor: '#7C3AED',
    expertise: ['資訊安全', '網路安全', '漏洞分析'],
    courses: ['資訊安全概論', '網路攻防實務'],
  },
  {
    name: '張凱翔',
    title: '副教授',
    department: '資訊工程學系',
    email: 'kaixiang.zhang@example.edu',
    office: '資訊館 R516',
    bio: '專長為分散式系統、雲端運算與容器技術，研究高可用服務的設計與監控方法，課程強調以小型專案理解現代後端服務從開發到部署的完整流程。',
    avatarColor: '#C2410C',
    expertise: ['雲端運算', '分散式系統', '容器技術'],
    courses: ['雲端運算概論', '分散式系統'],
  },
  {
    name: '吳佳穎',
    title: '助理教授',
    department: '資訊工程學系',
    email: 'jiaying.wu@example.edu',
    office: '資訊館 R410',
    bio: '研究人機互動、使用者經驗與無障礙科技，關注不同使用者如何理解與操作數位產品，並帶領學生從訪談、原型到測試完成以人為本的設計流程。',
    avatarColor: '#BE185D',
    expertise: ['人機互動', '使用者經驗', '無障礙設計'],
    courses: ['人機互動', '使用者介面設計'],
  },
  {
    name: '許家豪',
    title: '教授',
    department: '資訊工程學系',
    email: 'jiahao.xu@example.edu',
    office: '資訊館 R702',
    bio: '長期投入軟體工程、程式分析與測試自動化研究，重視可維護性及團隊協作，指導學生透過版本控制、測試與重構建立穩定且可持續演進的軟體。',
    avatarColor: '#334155',
    expertise: ['軟體工程', '程式分析', '軟體測試'],
    courses: ['軟體工程', '軟體測試'],
  },
  {
    name: '李若晴',
    title: '副教授',
    department: '資訊管理學系',
    email: 'ruoqing.li@example.edu',
    office: '商學館 M305',
    bio: '研究商業智慧、資料視覺化與決策支援系統，關心資料如何轉化為可理解的管理洞察，並以校園與企業案例訓練學生提出具體的資料分析建議。',
    avatarColor: '#0369A1',
    expertise: ['商業智慧', '資料視覺化', '決策支援'],
    courses: ['商業智慧', '資料視覺化'],
  },
  {
    name: '周品睿',
    title: '助理教授',
    department: '資訊管理學系',
    email: 'pinrui.zhou@example.edu',
    office: '商學館 M312',
    bio: '專注數位轉型、企業流程與資訊系統導入，探討組織如何有效採用新科技，課程結合流程分析與專案提案，培養學生溝通技術和管理需求的能力。',
    avatarColor: '#15803D',
    expertise: ['數位轉型', '企業流程', '資訊系統'],
    courses: ['管理資訊系統', '企業流程管理'],
  },
  {
    name: '鄭雅文',
    title: '教授',
    department: '資訊管理學系',
    email: 'yawen.zheng@example.edu',
    office: '商學館 M508',
    bio: '研究電子商務、數位行銷與消費者行為，關注平台設計如何影響使用者決策，並引導學生從資料、倫理與商業價值等面向評估數位服務策略。',
    avatarColor: '#A21CAF',
    expertise: ['電子商務', '數位行銷', '消費者行為'],
    courses: ['電子商務', '數位行銷分析'],
  },
  {
    name: '蔡承恩',
    title: '副教授',
    department: '資訊管理學系',
    email: 'chengen.cai@example.edu',
    office: '商學館 M416',
    bio: '專長為資料探勘、推薦系統與顧客分析，研究如何在尊重隱私的前提下發掘行為模式，並以可重現的分析流程訓練學生驗證假設與解讀模型結果。',
    avatarColor: '#B45309',
    expertise: ['資料探勘', '推薦系統', '機器學習'],
    courses: ['資料探勘', '顧客資料分析'],
  },
  {
    name: '郭怡君',
    title: '助理教授',
    department: '資訊管理學系',
    email: 'yijun.guo@example.edu',
    office: '商學館 M309',
    bio: '研究資訊隱私、科技倫理與平台治理，分析數位服務中的資料責任與風險，課堂透過案例討論協助學生辨識利害關係人並提出兼顧創新與權益的方案。',
    avatarColor: '#DC2626',
    expertise: ['資訊隱私', '科技倫理', '平台治理'],
    courses: ['資訊倫理', '資訊安全管理'],
  },
  {
    name: '何宇軒',
    title: '教授',
    department: '資訊管理學系',
    email: 'yuxuan.he@example.edu',
    office: '商學館 M602',
    bio: '投入資訊系統專案管理、敏捷方法與團隊協作研究，關心專案決策和溝通品質，並讓學生以角色分工、迭代交付及風險檢討實際體驗專案生命週期。',
    avatarColor: '#475569',
    expertise: ['專案管理', '敏捷開發', '軟體工程'],
    courses: ['資訊專案管理', '敏捷產品開發'],
  },
  {
    name: '楊子謙',
    title: '教授',
    department: '電機工程學系',
    email: 'ziqian.yang@example.edu',
    office: '工程館 E718',
    bio: '研究嵌入式系統、物聯網與邊緣運算，著重感測裝置到雲端服務的完整整合，指導學生以實作驗證效能、耗電與可靠度之間的工程取捨。',
    avatarColor: '#1D4ED8',
    expertise: ['嵌入式系統', '物聯網', '邊緣運算'],
    courses: ['嵌入式系統', '物聯網實務'],
  },
  {
    name: '謝佩珊',
    title: '副教授',
    department: '電機工程學系',
    email: 'peishan.xie@example.edu',
    office: '工程館 E614',
    bio: '專注數位訊號處理、語音辨識與音訊分析，研究智慧裝置中的聲音理解技術，並帶領學生從訊號基礎、特徵設計到模型評估完成可展示的應用。',
    avatarColor: '#9333EA',
    expertise: ['數位訊號處理', '語音辨識', '音訊分析'],
    courses: ['訊號與系統', '語音處理'],
  },
  {
    name: '羅冠廷',
    title: '助理教授',
    department: '電機工程學系',
    email: 'guanting.luo@example.edu',
    office: '工程館 E509',
    bio: '研究機器人控制、自主導航與感測融合，關注機器如何在不確定環境中安全行動，課程以模擬和實體平台協助學生理解控制演算法的限制與驗證方式。',
    avatarColor: '#0F766E',
    expertise: ['機器人', '自動控制', '感測融合'],
    courses: ['自動控制', '機器人導論'],
  },
  {
    name: '蘇婉婷',
    title: '教授',
    department: '電機工程學系',
    email: 'wanting.su@example.edu',
    office: '工程館 E802',
    bio: '研究通訊網路、無線系統與網路效能分析，探討高密度裝置環境中的資源配置問題，並重視以數據和實驗結果支持可靠的通訊系統設計決策。',
    avatarColor: '#BE123C',
    expertise: ['通訊網路', '無線通訊', '網路'],
    courses: ['計算機網路', '無線通訊系統'],
  },
  {
    name: '方俊傑',
    title: '副教授',
    department: '電機工程學系',
    email: 'junjie.fang@example.edu',
    office: '工程館 E521',
    bio: '投入積體電路設計、低功耗系統與硬體加速研究，關心演算法如何有效落實於晶片，帶領學生從規格、模擬到驗證理解硬體設計的完整流程。',
    avatarColor: '#A16207',
    expertise: ['積體電路', '低功耗設計', '硬體加速'],
    courses: ['數位邏輯設計', '積體電路設計'],
  },
  {
    name: '沈詩涵',
    title: '助理教授',
    department: '電機工程學系',
    email: 'shihan.shen@example.edu',
    office: '工程館 E412',
    bio: '研究智慧電網、能源資料分析與預測模型，關注再生能源導入後的供需平衡，並引導學生結合電力知識和資料方法評估節能與調度策略。',
    avatarColor: '#047857',
    expertise: ['智慧電網', '能源管理', '資料分析'],
    courses: ['電力系統', '智慧能源分析'],
  },
  {
    name: '杜明哲',
    title: '教授',
    department: '數位學習與教育科技學系',
    email: 'mingzhe.du@example.edu',
    office: '人文館 H608',
    bio: '研究數位學習、學習分析與適性教學，關注學習資料如何協助教師理解學生需求，並以教學現場問題為起點設計可驗證且重視倫理的教育科技方案。',
    avatarColor: '#1E40AF',
    expertise: ['數位學習', '學習分析', '適性教學'],
    courses: ['數位學習導論', '學習分析'],
  },
  {
    name: '賴欣怡',
    title: '副教授',
    department: '數位學習與教育科技學系',
    email: 'xinyi.lai@example.edu',
    office: '人文館 H512',
    bio: '專注線上課程設計、教學互動與學習動機研究，探討不同媒體和活動如何影響參與，並協助學生運用需求分析與形成性評量持續改善課程。',
    avatarColor: '#C026D3',
    expertise: ['教學設計', '線上學習', '學習動機'],
    courses: ['教學設計', '線上課程製作'],
  },
  {
    name: '潘昱安',
    title: '助理教授',
    department: '數位學習與教育科技學系',
    email: 'yuan.pan@example.edu',
    office: '人文館 H407',
    bio: '研究教育遊戲、遊戲化學習與互動敘事，關心遊戲機制是否真正支持學習目標，課程要求學生透過原型測試與學習證據反覆修正整體設計。',
    avatarColor: '#EA580C',
    expertise: ['教育遊戲', '遊戲化學習', '互動敘事'],
    courses: ['教育遊戲設計', '互動媒體製作'],
  },
  {
    name: '邱郁庭',
    title: '教授',
    department: '數位學習與教育科技學系',
    email: 'yuting.qiu@example.edu',
    office: '人文館 H702',
    bio: '投入教育資料探勘、學習診斷與視覺化研究，致力於把複雜資料轉為教師可採取的教學行動，並重視模型公平性、資料隱私與結果解釋。',
    avatarColor: '#0369A1',
    expertise: ['教育資料探勘', '學習診斷', '資料視覺化'],
    courses: ['教育資料探勘', '教育統計與視覺化'],
  },
  {
    name: '高以柔',
    title: '副教授',
    department: '數位學習與教育科技學系',
    email: 'yirou.gao@example.edu',
    office: '人文館 H518',
    bio: '研究擴增實境、沉浸式學習與體驗設計，探討虛實整合如何支持抽象概念理解，帶領學生從使用情境、互動原型到學習成效完成設計驗證。',
    avatarColor: '#7E22CE',
    expertise: ['擴增實境', '沉浸式學習', '體驗設計'],
    courses: ['擴增實境應用', '沉浸式學習設計'],
  },
  {
    name: '葉書銘',
    title: '助理教授',
    department: '數位學習與教育科技學系',
    email: 'shuming.ye@example.edu',
    office: '人文館 H415',
    bio: '專長為生成式人工智慧、智慧導師與教育對話系統，研究如何讓人工智慧安全支持學習者，並強調以學習目標、使用者測試和責任設計評估工具價值。',
    avatarColor: '#0D9488',
    expertise: ['生成式人工智慧', '智慧導師', '人機互動'],
    courses: ['教育人工智慧', '智慧學習系統'],
  },
]
